services:
    bot:
        build: 
            context: .
            dockerfile: Dockerfile.bot
        env_file:
            - .env
        volumes:
            - ./db:/app/db
        restart: unless-stopped
